---
- name: Install haproxy
  package:
    name: haproxy
    state: installed

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: reload haproxy

- name: Ensure haproxy is started
  systemd:
    name: haproxy
    state: started
    enabled: true