---
- name: Gather special node facts
  hosts: gather
  become: true
  gather_facts: false

  tasks:
    - name: Gather all facts
      ansible.builtin.setup:

- name: Deploy etcd on PostgreSQL nodes
  hosts: etcd
  become: true # Not needed for root but we won't use root later

  vars:
    etcd_master_group_name: "{{ postgresql_cluster_name  }}"
    etcd_cluster: "{% for host in groups[etcd_master_group_name] %}{{ hostvars[host]['ansible_nodename'] }}={{ etcd_scheme }}{{ hostvars[host]['etcd_address_cluster'] }}:{{ etcd_port_peer }}{% if not loop.last %},{% endif %}{% endfor %}"  # yamllint disable-line rule:line-length
    etcd_cluster_name: "{{ postgresql_cluster_name  }}"
    etcd_iface_cluster: ens18

  roles:
    - role: zorlin.etcd_cluster
      etcd_secure: true

- name: Deploy PostgreSQL and Patroni on PostgreSQL nodes
  hosts: postgresql
  become: true

  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: secrets_file

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
        name: secrets
      when: secrets_file.stat.exists

  vars_files:
    - vars/secrets.yml

  roles:
    - patroni_system_user
    - patroni_certs
    - role: zorlin.patroni
